dependencies:
- name: influxdb
  version: ">=0.11.0"
#  version: "~0.9.3"
  repository: "@stable"
#  repository: https://kubernetes-charts.storage.googleapis.com/
#  condition: influxdb.enabled
  tags:
    - db
- name: kapacitor
  version: ">=1.1.0"
  repository: "@stable"
#  condition: kapacitor.enabled
  tags:
    - engine
- name: chronograf
  version: ">=0.4.5"
  repository: "@stable"
#  condition: chronograf.enabled
  tags:
    - dashboard
    - admin
- name: telegraf
  version: ">=0.3.3"
  repository: "@stable"
#  condition: telegraf.enabled
  tags:
    - daemon
